export const HOME = "/"
export const FAVORİTES ="/Favorites"
export const USERPROFİLE ="/UserProfile"
export const CART  ="/Cart"

export const SHOP ="/Shop"
export const BLOG ="/Blog"
export const ABOUT ="/About"
export const CONTACT ="/Contact"
// export const NOTFOUND ="/*"